import { useState } from "react";
import { Download, Share2, Copy, Check, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AnalysisData, CompetitorData } from "./types";
import { toast } from "@/hooks/use-toast";

interface ExportShareProps {
  brandName: string;
  website: string;
  data: AnalysisData;
  competitors: CompetitorData[];
}

export function ExportShare({ brandName, website, data, competitors }: ExportShareProps) {
  const [copied, setCopied] = useState(false);

  const generateTextReport = (): string => {
    let report = `AI BRAND INTELLIGENCE REPORT\n`;
    report += `${"=".repeat(40)}\n\n`;
    report += `Brand: ${brandName}\n`;
    report += `Website: ${website}\n`;
    report += `Date: ${new Date().toLocaleDateString()}\n`;
    report += `Overall Score: ${data.overallScore}/100 (${data.status.toUpperCase()})\n\n`;

    report += `ENGINE RESULTS\n${"-".repeat(30)}\n`;
    data.engines.forEach(eng => {
      report += `\n${eng.engine}: ${eng.mentioned ? "MENTIONED" : "NOT FOUND"} | Sentiment: ${eng.sentiment.toUpperCase()}`;
      if (eng.position) report += ` | Position: #${eng.position}`;
      report += `\n  ${eng.snippet}\n`;
      report += `  Reasons: ${eng.reasons.join(", ")}\n`;
    });

    report += `\nVISIBILITY GAPS\n${"-".repeat(30)}\n`;
    data.gaps.forEach((gap, i) => { report += `${i + 1}. ${gap}\n`; });

    report += `\nIMPROVEMENT PLAN\n${"-".repeat(30)}\n`;
    data.improvementPlan.forEach((step, i) => {
      report += `${i + 1}. [${step.priority.toUpperCase()}] ${step.title}\n   ${step.description}\n`;
    });

    if (competitors.length > 0) {
      report += `\nCOMPETITOR BENCHMARK\n${"-".repeat(30)}\n`;
      competitors.forEach(c => {
        report += `${c.name}: ${c.score}/100 (${c.status})\n`;
      });
    }

    report += `\n${"=".repeat(40)}\nGenerated by Three Reach AI`;
    return report;
  };

  const downloadReport = () => {
    const report = generateTextReport();
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${brandName.replace(/\s+/g, "-").toLowerCase()}-ai-report-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Report downloaded", description: "Your AI intelligence report has been saved." });
  };

  const downloadCSV = () => {
    const rows = [
      ["Engine", "Mentioned", "Position", "Sentiment", "Snippet"],
      ...data.engines.map(e => [e.engine, e.mentioned ? "Yes" : "No", e.position?.toString() || "N/A", e.sentiment, `"${e.snippet}"`]),
    ];
    if (competitors.length > 0) {
      rows.push([], ["Competitor", "Score", "Status"]);
      competitors.forEach(c => rows.push([c.name, c.score.toString(), c.status]));
    }
    const csv = rows.map(r => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${brandName.replace(/\s+/g, "-").toLowerCase()}-ai-data-${new Date().toISOString().split("T")[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "CSV exported", description: "Data exported to CSV file." });
  };

  const copyShareLink = () => {
    const summary = `🔍 AI Brand Intelligence: ${brandName} scored ${data.overallScore}/100 (${data.status}) across ChatGPT, Gemini & Perplexity. ${data.gaps.length} visibility gaps identified. Powered by Three Reach AI.`;
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({ title: "Copied to clipboard", description: "Share-ready summary copied." });
  };

  return (
    <div className="flex items-center gap-2">
      <Button variant="outline" onClick={downloadReport} className="rounded-xl gap-1.5 h-9 border-border/60 shadow-none text-xs">
        <FileText className="h-3.5 w-3.5" /> Report
      </Button>
      <Button variant="outline" onClick={downloadCSV} className="rounded-xl gap-1.5 h-9 border-border/60 shadow-none text-xs">
        <Download className="h-3.5 w-3.5" /> CSV
      </Button>
      <Button variant="outline" onClick={copyShareLink} className="rounded-xl gap-1.5 h-9 border-border/60 shadow-none text-xs">
        {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
        {copied ? "Copied!" : "Share"}
      </Button>
    </div>
  );
}
